### PR TITLE
fixed "works fine with concrete version 9"

### PR DESCRIPTION
**Pull request by Hmone23**

### CODE REVIEW

**Comment by biplobice** [comment]
@Hmone23 
You opened PR for `0.1.4` but against `release/0.2.0` branch!

**Comment by biplobice** [comment]
@Hmone23 
Please check the attached screen recording.

https://user-images.githubusercontent.com/2462951/163906070-68eee9ee-a962-453b-8267-1ea527b6605a.mp4

@nakazawazakan Please test it if you have some time.

**Comment by nakazawazakan** [comment]
@biplobice @Hmone23 
I got the same error as Biplob had got.

**Comment by Hmone23** [comment]
@biplobice 
@nakazawazakan 

This error didn't happen in my local.
Have you added `driverOptions` in database.php?
Screen Shot 2022-04-27 at 10 52 35 AM

**Comment by biplobice** [comment]
@Hmone23 
Thanks.
It works by adding the `driverOptions`. But It would be nice if you can remove that dependency.

**Pull request merged**
