### PR TITLE
fixed "works fine with concrete version 9"

### PR DESCRIPTION
**Pull request by Hmone23**
Fixed to work with concrete version 9.
Please confirm PR.

### CODE REVIEW

**Comment by biplobice** [comment]
@Hmone23 
Can you please open the PR against `release/0.1.4` branch?

FYI, I got the following error when I added a page and discarded draft without doing anything.

```
Failed to create closure from callable: non-static method C5jRatings\EventListener\PageEventListener::onPageDelete() should not be called statically
```

### How to Reproduce
- Add a page 
- Don't do anything
- Discard the draft from the edit mode.

It may exist in the concrete v8 as well. Please check.

**Comment by Hmone23** [comment]
@biplobice 

> How to Reproduce
> 
> Add a page
> Don't do anything
> Discard the draft from the edit mode.
> It may exist in the concrete v8 as well. Please check.

It does not happen in my local.
Could you give me screen recording?

**Comment by biplobice** [comment]
Check here https://filetransfer.io/data-package/kkngGpGb#link

**Comment by Hmone23** [comment]
@biplobice 

> Check here https://filetransfer.io/data-package/kkngGpGb#link

I tested according to your screen recording.
my local works fine 

https://user-images.githubusercontent.com/43093665/162170911-53c6a8d5-a51e-49b4-aa9c-3deb2db0fbdb.mov

**Pull request closed without merging**
