### PR TITLE
feature: separate js function

### PR DESCRIPTION
**Pull request by SashaMcr**

### CODE REVIEW

**Comment by biplobice** [comment]
@SashaMcr 
Thank you.

Could you please explain why introducing a new action is necessary? It seems that the existing `get_ratings` action could be modified to handle both single and multiple `cID` values by adding a condition. This approach would ensure compatibility with existing templates.

**Comment by SashaMcr** [comment]
@biplobice 

I thought about different action to avoid logic overload: different action for different results - single data or array of data
for easier understanding

yes, you are right, we can check condition  "cID is array" and avoid using new action

if it is needed, i can implement this way

**Comment by biplobice** [comment]
@SashaMcr 
Yes, I'd prefer that.
Thanks in advance.

**Comment by SashaMcr** [comment]
@biplobice 

fixed

**Pull request merged**
